### ISSUE TITLE
error when switching to Babel space name

### ISSUE THREAD

**Issue by elz64** [virtudraft/CrossContextsSettings#1]
Hi,

Nice components. It displays my web + en CX for core spacename when launched, but if I switch to "babel" (the only other space name available), it fires the following error:

Code: 404 Not Found
{"success":false,"message":"Processeur getareas introuvable.","total":0,"data":[],"object":[]}

And then no way to switch back to core display, the select is 'dead'

**Comment by goldsky** [comment]
seems working for me.
have you tried to rerun installation? or redownload the package?

**Comment by goldsky** [comment]
I'm closing this since it works for me.
Pls reply if you have new feedback.
