### ISSUE TITLE
Some issue with 1.0.2

### ISSUE THREAD

**Issue by Jako** [virtudraft/CrossContextsSettings#12]
![Screenshot](https://cloud.githubusercontent.com/assets/148371/9060326/e43d8dea-3ab2-11e5-9373-5ccdea21733e.png)

Not sure where this issue is happening. The context columns are missing and the row contains only 'textfield'. No error messages in MODX error log and in the Browser console.

**Comment by goldsky** [comment]
How many context do you have?

**Comment by goldsky** [comment]
How did you create the settings?

**Comment by Jako** [comment]
There are 3 contexts (web, de, fr) and I have created some of the settings with CrossContextsSettings 1.0.0 and below. Most settings are not set in web if that could be a problem (but base_url is present in all 3 contexts).

**Comment by JensWolff** [comment]
Same error here.. Also with 3 contexts (web, en, fr)

**Comment by goldsky** [comment]
Found the culprit.
I will release new update in minutes.

**Comment by goldsky** [comment]
you can download it now

**Comment by Jako** [comment]
Thanks!
