### ISSUE TITLE
Nothing in grid

### ISSUE THREAD

**Issue by artsur** [virtudraft/CrossContextsSettings#14]
I have 7 contexts. In the CrossContextsSettings panel I see nothing. Panel "Clear cache" also is empty.
However, on the other site with 3 contexts it works fine. 
How can I make it workable on site with big number of contexts?

**Comment by goldsky** [comment]
Modx version?

**Comment by artsur** [comment]
MODX Revolution 2.4.2-pl (traditional)

**Comment by goldsky** [comment]
what's the error on your web console?

**Comment by artsur** [comment]
There is no errors in modx console. However, if you meant errors in the web-browser's console, so it is: "unreachable code after return statement". This error appears on any pages. It is not only on CrossContextSetting's page

**Comment by goldsky** [comment]
download 1.0.4-pl

**Comment by artsur** [comment]
Thank you so much! It's working well!
