### ISSUE TITLE
NameSpace dropdown

### ISSUE THREAD

**Issue by minagerges** [virtudraft/CrossContextsSettings#7]
NameSpace dropdown shows only one line, and upon changing the name space the dropsown doesn't work anymore.

**Comment by goldsky** [comment]
being discussed on MODX's repo.
It's an update that breaks everything.

**Comment by minagerges** [comment]
Modx 2.3.1, if that makes a difference.

Kind regards,
Mina Gerges

**Comment by goldsky** [comment]
this also happens for the current MODX release.
